#!/bin/bash

shopt -s nullglob globstar

password_files=( ~/.password-store/**/*.gpg )
password_files=( "${password_files[@]##*/.password-store/}" )
password_files=( "${password_files[@]%.gpg}" )

#password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")
password=$(printf '%s\n' "${password_files[@]}" | dmenu -l 15 -fn '-*-terminus-medium-r-*-*-18-*-*-*-*-*-*-*' "$@")

pass -c "$password"
