#!/bin/bash

run_rofi="
command -v 'rofi' > /dev/null 2>&1 && rofi $@
"

get_id() {
	local id=$(xprop -root _NET_ACTIVE_WINDOW)
	echo ${id##* } # extract id
}

get_vm() {
	local id=$(get_id)
	local vm=$(xprop -id $id | grep '_QUBES_VMNAME(STRING)')
	local vm=${vm#*\"} # extract vmname
	echo ${vm%\"*} # extract vmname
}

main() {
	local vm=$(get_vm)
	if [[ -n "$vm" ]]; then
		qvm-run "$vm" "bash -c '$run_rofi'"
	else # run dmenu in dom0
		exec bash -c "i3-dmenu-desktop --dmenu=\"dmenu -nb #d2d2d2 -nf #000000 -sb #63a0ff\""
	fi
}

main
